"""Token and cost estimation for Groq usage.

This module is responsible ONLY for pure token/cost calculation. It
contains no persistence, quota-enforcement, or FastAPI logic. Exact
token counts are not available from the existing `llm.client.GroqClient`
wrapper (it returns plain text), so token counts are estimated using a
character-based heuristic; this is documented as an approximation
suitable for budget tracking, not billing-grade accounting.
"""

from pydantic import BaseModel

_CHARS_PER_TOKEN = 4.0

_MODEL_PRICING_PER_MILLION_TOKENS: dict[str, tuple[float, float]] = {
    "llama-3.3-70b-versatile": (0.59, 0.79),
    "llama-3.1-8b-instant": (0.05, 0.08),
}
_DEFAULT_PRICING_PER_MILLION_TOKENS: tuple[float, float] = (0.59, 0.79)


class UsageEstimate(BaseModel):
    """An estimated token/cost breakdown for a single agent call.

    Attributes:
        model: Name of the Groq model used.
        prompt_tokens: Estimated prompt token count.
        completion_tokens: Estimated completion token count.
        total_tokens: Sum of prompt and completion tokens.
        cost_usd: Estimated USD cost of the call.
    """

    model: str
    prompt_tokens: int
    completion_tokens: int
    total_tokens: int
    cost_usd: float


def estimate_tokens(text: str) -> int:
    """Estimate the token count of a piece of text.

    Uses a simple character-based heuristic (~4 characters per token),
    which is a reasonable approximation for English clinical text
    without requiring a model-specific tokenizer dependency.

    Args:
        text: The text to estimate token count for.

    Returns:
        int: The estimated token count, at least 1 for non-empty text.
    """
    if not text:
        return 0
    return max(1, round(len(text) / _CHARS_PER_TOKEN))


def calculate_cost(model: str, prompt_tokens: int, completion_tokens: int) -> float:
    """Calculate the estimated USD cost of a call given its token counts.

    Args:
        model: Name of the Groq model used.
        prompt_tokens: Prompt token count.
        completion_tokens: Completion token count.

    Returns:
        float: The estimated USD cost, rounded to 6 decimal places.
    """
    prompt_price, completion_price = _MODEL_PRICING_PER_MILLION_TOKENS.get(
        model, _DEFAULT_PRICING_PER_MILLION_TOKENS
    )
    cost = (prompt_tokens / 1_000_000) * prompt_price + (
        completion_tokens / 1_000_000
    ) * completion_price
    return round(cost, 6)


def estimate_usage(model: str, prompt_text: str, completion_text: str) -> UsageEstimate:
    """Estimate the full token/cost breakdown for a single agent call.

    Args:
        model: Name of the Groq model used.
        prompt_text: The text sent to the model (question plus context).
        completion_text: The text generated by the model.

    Returns:
        UsageEstimate: The estimated prompt/completion/total tokens and
            USD cost.
    """
    prompt_tokens = estimate_tokens(prompt_text)
    completion_tokens = estimate_tokens(completion_text)
    cost = calculate_cost(model, prompt_tokens, completion_tokens)

    return UsageEstimate(
        model=model,
        prompt_tokens=prompt_tokens,
        completion_tokens=completion_tokens,
        total_tokens=prompt_tokens + completion_tokens,
        cost_usd=cost,
    )
