"""add usage_logs and quotas tables

Revision ID: 3177536bc2c6
Revises: 0001_initial_schema
Create Date: 2026-07-10 14:41:11.673121

"""

from collections.abc import Sequence

import sqlalchemy as sa

import database.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3177536bc2c6"
down_revision: str | None = "0001_initial_schema"
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "quotas",
        sa.Column("id", database.models.GUID(), nullable=False),
        sa.Column("user_id", database.models.GUID(), nullable=False),
        sa.Column("daily_request_count", sa.Integer(), nullable=False),
        sa.Column("daily_reset_date", sa.Date(), nullable=False),
        sa.Column("monthly_token_count", sa.Integer(), nullable=False),
        sa.Column("monthly_cost_usd", sa.Float(), nullable=False),
        sa.Column("monthly_reset_month", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_quotas_user_id"), "quotas", ["user_id"], unique=True)
    op.create_table(
        "usage_logs",
        sa.Column("id", database.models.GUID(), nullable=False),
        sa.Column("user_id", database.models.GUID(), nullable=False),
        sa.Column("conversation_id", database.models.GUID(), nullable=True),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["conversation_id"], ["conversations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usage_logs_conversation_id"), "usage_logs", ["conversation_id"], unique=False
    )
    op.create_index(op.f("ix_usage_logs_user_id"), "usage_logs", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_logs_user_id"), table_name="usage_logs")
    op.drop_index(op.f("ix_usage_logs_conversation_id"), table_name="usage_logs")
    op.drop_table("usage_logs")
    op.drop_index(op.f("ix_quotas_user_id"), table_name="quotas")
    op.drop_table("quotas")
    # ### end Alembic commands ###
